equipment_service/equipment_service/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maintenance.urls')),
]

equipment_service/maintenance/urls.py
from django.urls import path
from .views import equipment_list, plan_list, generate_plan_view, dashboard

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('equipment/', equipment_list, name='equipment_list'),
    path('plans/', plan_list, name='plan_list'),
    path('plans/<int:equipment_id>/', plan_list),
    path('generate/<int:equipment_id>/', generate_plan_view, name='generate_plan'),
]

equipment_service/maintenance/models.py
from django.db import models

class Equipment(models.Model):
    name = models.CharField("Название оборудования", max_length=100)
    equipment_type = models.CharField("Тип оборудования", max_length=100)
    manufacturer = models.CharField("Производитель", max_length=100)
    start_date = models.DateField("Дата ввода в эксплуатацию")

    def __str__(self):
        return self.name


class MaintenanceNorm(models.Model):
    equipment = models.OneToOneField(
        Equipment,
        on_delete=models.CASCADE,
        verbose_name="Оборудования"
    )
    to_period = models.IntegerField("ТО (мес.)")
    tr_period = models.IntegerField("ТР (мес.)")
    kr_period = models.IntegerField("КР (мес.)")

    def __str__(self):
        return f"Нормативы для {self.equipment}"


class MaintenancePlan(models.Model):
    WORK_TYPES = [
        ('ТО', 'Технический осмотр'),
        ('ТР', 'Технический ремонт'),
        ('КР', 'Капитальный ремонт'),
    ]

    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    work_type = models.CharField(max_length=2, choices=WORK_TYPES)
    planned_date = models.DateField("Плановая дата")
    status = models.CharField("Статус", max_length=20, default="Запланировано")

    def __str__(self):
        return f"{self.work_type} - {self.equipment}"

equipment_service/maintenance/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Equipment, MaintenancePlan, MaintenanceNorm
from .utils import generate_plan
from collections import defaultdict
from calendar import month_name

def equipment_list(request):
    equipments = Equipment.objects.all()
    return render(request, 'maintenance/equipment_list.html', {'equipments': equipments})

def plan_list(request, equipment_id=None):
    if equipment_id:
        plans = MaintenancePlan.objects.filter(equipment__id=equipment_id).order_by('planned_date')
    else:
        plans = MaintenancePlan.objects.order_by('planned_date')
    
    calendar = defaultdict(list)
    for p in plans:
        month_year = f"{month_name[p.planned_date.month]} {p.planned_date.year}"
        calendar[month_year].append(p)
    
    return render(
        request,
        'maintenance/plan_list.html',
        {'calendar': dict(calendar)}
    )

def generate_plan_view(request, equipment_id):
    equipment = get_object_or_404(Equipment, id=equipment_id)
    norm = get_object_or_404(MaintenanceNorm, equipment=equipment)

    generate_plan(equipment, norm, months=12)

    return redirect(f'/plans/{equipment.id}/')

def dashboard(request):
    equipments = Equipment.objects.all()
    plans = MaintenancePlan.objects.order_by('planned_date')[:15]

    return render(
        request,
        'maintenance/dashboard.html',
        {
            'equipments': equipments,
            'plans': plans
        }
    )

equipment_service/maintenance/templates/maintenance/dashboard.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Система ТО и ремонтов</title>
</head>
<body>

<h1>Панель управления</h1>

<hr>

<h2>Оборудование</h2>
<ul>
{% for e in equipments %}
    <li>
        {{ e.name }} ({{ e.equipment_type }})
        —
        <a href="/generate/{{ e.id }}/">Сформировать план</a>
    </li>
{% empty %}
    <li>Оборудование отсутствует</li>
{% endfor %}
</ul>

<hr>

<h2>Ближайшие работы</h2>
<ul>
{% for p in plans %}
    <li>
        {{ p.planned_date|date:"d.m.Y" }}
        —
        {{ p.get_work_type_display }}
        —
        {{ p.equipment.name }}
    </li>
{% empty %}
    <li>План-график пуст</li>
{% endfor %}
</ul>

<hr>

<h2>Навигация</h2>
<ul>
    <li><a href="/admin/">Администрирование</a></li>
    <li><a href="/equipment/">Все оборудование</a></li>
    <li><a href="/plans/">Полный план-график</a></li>
</ul>

</body>
</html>

equipment_service/maintenance/templates/maintenance/equipment_list.html
<h1>Оборудование</h1>

<ul>
{% for e in equipments %}
  <li>
    {{ e.name }} ({{ e.equipment_type }})
    —
   <a href="/generate/{{ e.id }}/">
      Сформировать план
    </a>
  </li>
{% endfor %}
</ul>

equipment_service/maintenance/templates/maintenance/plan_list.html
<h1>Календарный план-график </h1>

{% for month, plans in calendar.items %}
  <h2>{{ month }}</h2>
  <ul>
  {% for p in plans %}
    <li>{{ p.planned_date|date:"d.m.Y" }} — {{ p.get_work_type_display }} — {{ p.equipment.name }}</li>
  {% endfor %}
  </ul>
{% endfor %}